databases:
  - name: mysite
    databaseName: mysite
    user: mysite
    plan: free


services:
  - type: web
    name: mysite
    env: docker
    dockerfilePath: ./production.Dockerfile
    repo: https://github.com/bjvta/ministry-collections
    region: oregon
    branch: main
    plan: free
    dockerCommand: "bundle exec puma -C config/puma.rb"
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: SECRET_KEY_BASE
        sync: false # placeholder for a value to be added in the dashboard